[project]
name = 'liquid-stacking-stx'
description = ''
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []
[contracts.liquid-stacking]
path = 'contracts/liquid-stacking.clar'
clarity_version = 1
epoch = 2.0

[contracts.stacking-rewards]
path = 'contracts/stacking-rewards.clar'
clarity_version = 1
epoch = 2.0

[contracts.stacking-stat]
path = 'contracts/stacking-stat.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
